engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
   paths:
   - "**.js"
exclude_paths:
- "gulpfile.babel.js"
- "careen.js"
- "README.md"
- "Procfile"
- "app.json"
- "package.json"
- "migrations/**/*"
- "config/**/*"
- "test/**/*"
